// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzMcd2-dsB10ULWDhwNvfWFDtnZ7GQBgU',
    appId: '1:626816773624:web:536c98f87b5142bd293a0d',
    messagingSenderId: '626816773624',
    projectId: 'zeabix-test-project',
    authDomain: 'zeabix-test-project.firebaseapp.com',
    storageBucket: 'zeabix-test-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyABHvmyM-rSRaktFnbBxWFsjtNmJsP5_eI',
    appId: '1:626816773624:android:fced9c53b095c1b5293a0d',
    messagingSenderId: '626816773624',
    projectId: 'zeabix-test-project',
    storageBucket: 'zeabix-test-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDiewAmXrUw4PIZGpACT4sOfSM_b3pXAuE',
    appId: '1:626816773624:ios:43eb6586a86e7986293a0d',
    messagingSenderId: '626816773624',
    projectId: 'zeabix-test-project',
    storageBucket: 'zeabix-test-project.appspot.com',
    iosBundleId: 'com.example.taskViewerZeabix',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDiewAmXrUw4PIZGpACT4sOfSM_b3pXAuE',
    appId: '1:626816773624:ios:43eb6586a86e7986293a0d',
    messagingSenderId: '626816773624',
    projectId: 'zeabix-test-project',
    storageBucket: 'zeabix-test-project.appspot.com',
    iosBundleId: 'com.example.taskViewerZeabix',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzMcd2-dsB10ULWDhwNvfWFDtnZ7GQBgU',
    appId: '1:626816773624:web:14fb675f1335b598293a0d',
    messagingSenderId: '626816773624',
    projectId: 'zeabix-test-project',
    authDomain: 'zeabix-test-project.firebaseapp.com',
    storageBucket: 'zeabix-test-project.appspot.com',
  );
}
